language: cpp

sudo: false

#script:
  #  - wget https://dl.bintray.com/kaitai-io/universal/0.8/kaitai-struct-compiler-0.8.zip
  #  - unzip kaitai-struct-compiler-0.8.zip
  #  - mkdir kaitai_out
  #  - ./kaitai-struct-compiler-0.8/bin/kaitai-struct-compiler -t cpp_stl --outdir kaitai_out kaitai_defs/*.ksy
  #  - ls kaitai_out
  #  - tail -n +1 kaitai_out/*


cache:
  directories:
    - lib/curl-7.57.0

git:
  depth: 1

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'kwstyle']
      env: CXX_P=g++-7 CC_P=gcc-7 NOPCH=0

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-7', 'ubuntu-toolchain-r-test']
          packages: ['clang-7', 'libstdc++6', 'libstdc++-6-dev', 'kwstyle']
      env: CXX_P=clang++-7 CC_P=clang-7 NOPCH=0

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-7', 'ubuntu-toolchain-r-test']
          packages: ['clang-7', 'libstdc++6', 'libstdc++-6-dev']
      env: CXX_P=clang++-7 CC_P=clang-7 NOPCH=1

before_install:
  - cd bin-build
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - chmod +x ninja
  - export PATH=$TRAVIS_BUILD_DIR/bin-build:$PATH
  - ./ninja --version

before_script:
  - echo 'Configure...' && echo -en 'travis_fold:start:script.configure\\r'
  - export CXX=$CXX_P
  - export CC=$CC_P
  - cmake .. -G Ninja -DNO_PCH=$NOPCH
  - echo -en 'travis_fold:end:script.configure\\r'

script:
  - echo 'Build...' && echo -en 'travis_fold:start:script.build\\r'
  - ./ninja -j 2
  - echo -en 'travis_fold:end:script.build\\r'

  - echo 'Tests...' && echo -en 'travis_fold:start:script.tests\\r'
  - |
    if [[ "$NOPCH" == "0" ]]; then
      ctest -j 2 --output-on-failure --repeat-until-fail 5 || travis_terminate 1;
    fi
  - echo -en 'travis_fold:end:script.tests\\r'
  - echo 'Style...' && echo -en 'travis_fold:start:script.style\\r'
  - |
    if [[ "$NOPCH" == "0" ]]; then
      cd ../testsuite/style
      ./checknl.py -q || travis_terminate 1;
      ./checkstyle.py -q || travis_terminate 1;
    fi
  - echo -en 'travis_fold:end:script.style\\r'

notifications:
  email:
    - polteam@polserver.com
