language: cpp

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    #ref: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - george-edison55-precise-backports # cmake 3.2.3
    #ref: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    packages:
      - gcc-5
      - g++-5
      - clang-3.8
      - cmake
      - cmake-data
      - python3

before_install:
  - cd lib
  - tar xjf boost_1_55_0.tar.bz2
  - cd ../pol-core/bin-build
  - chmod a+x build_linux.sh

script:
  - echo 'Configure...' && echo -en 'travis_fold:start:script.configure\\r'
  - export TRAVIS_CI=1
  - if [ "$CXX" = "g++" ]; then 
      export CXX="g++-5" CC="gcc-5";
    fi
  - if [ "$CXX" = "clang++" ]; then 
      export CXX="clang++-3.8" CC="clang-3.8";
    fi
  - echo -en 'travis_fold:end:script.configure\\r'

  - echo 'Build...' && echo -en 'travis_fold:start:script.build\\r'
  - ./build_linux.sh
  - echo -en 'travis_fold:end:script.build\\r'

  - echo 'Tests...' && echo -en 'travis_fold:start:script.tests\\r'
  - cd ../../testsuite/escript
  - ./performtests.py ../../pol-core/bin/ecompile ../../pol-core/bin/runecl -n 5;
  - echo -en 'travis_fold:end:script.tests\\r'

notifications:
  email:
    - polteam@polserver.com
  irc:
    channels:
      - "ircs://irc.darkmyst.org:6697/#pol"
    on_success: always # Those are the defaults. Should maybe use "change" afterwards.
    on_failure: always
